language: python
before_deploy:
  - wget "http://file-examples.com/wp-content/uploads/2017/02/zip_2MB.zip"
deploy:
  provider: releases
  api_key: $tk
  file: ./*.zip
  file_glob: true
  skip_cleanup: true
  on:
    branch: master
